-- ============================================================================
--  Faso Tuuma — V1 : schéma initial
--  Source de vérité : DIAGRAM.md
--  SQL portable H2 (dev, fichier) + PostgreSQL (prod).
--    - PK : BIGINT GENERATED BY DEFAULT AS IDENTITY (portable H2/PG)
--    - dates : TIMESTAMP WITH TIME ZONE (TIMESTAMPTZ), stockées en UTC
--    - GPS : DECIMAL(9,6) ; note : DECIMAL(2,1)
--  Dépendance circulaire person <-> media_file <-> app_user :
--    les deux FK qui la ferment sont ajoutées en fin de fichier via ALTER TABLE.
-- ============================================================================

-- ---------- Tables sans dépendance ----------

CREATE TABLE role (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uq_role_name UNIQUE (name)
);

CREATE TABLE address (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city     VARCHAR(255) NOT NULL,
    district VARCHAR(255),
    sector   VARCHAR(255),
    street   VARCHAR(255)
);

CREATE TABLE media_file (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name        VARCHAR(255) NOT NULL,
    stored_path          VARCHAR(512) NOT NULL,
    content_type         VARCHAR(100) NOT NULL,
    size_bytes           BIGINT       NOT NULL,
    uploaded_by_user_id  BIGINT,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE person (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lastname      VARCHAR(255) NOT NULL,
    firstname     VARCHAR(255) NOT NULL,
    email         VARCHAR(255),
    photo_file_id BIGINT,
    CONSTRAINT uq_person_email UNIQUE (email)
);

-- ---------- Identité & rôles ----------

CREATE TABLE app_user (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id  BIGINT       NOT NULL,
    username   VARCHAR(255),
    phone      VARCHAR(30)  NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_app_user_person UNIQUE (person_id),
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT uq_app_user_phone UNIQUE (phone),
    CONSTRAINT fk_app_user_person FOREIGN KEY (person_id) REFERENCES person (id)
);

CREATE TABLE user_credential (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    password_hash     VARCHAR(255) NOT NULL,
    phone_verified_at TIMESTAMP WITH TIME ZONE,
    failed_attempts   INTEGER      NOT NULL DEFAULT 0,
    locked_until      TIMESTAMP WITH TIME ZONE,
    last_login        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_user_credential_user UNIQUE (user_id),
    CONSTRAINT fk_user_credential_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE
);

-- ---------- Catégories ----------

CREATE TABLE category (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name      VARCHAR(255) NOT NULL,
    slug      VARCHAR(255),
    CONSTRAINT uq_category_slug UNIQUE (slug),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category (id)
);

-- ---------- Enseignes (Metier) & dépendances ----------

CREATE TABLE metier (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id       BIGINT       NOT NULL,
    name                VARCHAR(255) NOT NULL,
    phone               VARCHAR(30),
    address_id          BIGINT,
    address_description TEXT,
    cover_file_id       BIGINT,
    description         TEXT,
    gps_lat             DECIMAL(9, 6),
    gps_lng             DECIMAL(9, 6),
    rating_avg          DECIMAL(2, 1) NOT NULL DEFAULT 0,
    rating_count        INTEGER       NOT NULL DEFAULT 0,
    is_published        BOOLEAN       NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_metier_owner FOREIGN KEY (owner_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_metier_address FOREIGN KEY (address_id) REFERENCES address (id),
    CONSTRAINT fk_metier_cover FOREIGN KEY (cover_file_id) REFERENCES media_file (id)
);

CREATE TABLE metier_category (
    metier_id   BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT pk_metier_category PRIMARY KEY (metier_id, category_id),
    CONSTRAINT fk_metier_category_metier FOREIGN KEY (metier_id) REFERENCES metier (id) ON DELETE CASCADE,
    CONSTRAINT fk_metier_category_category FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE
);

CREATE TABLE service (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metier_id   BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    price_min   BIGINT,
    price_max   BIGINT,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_service_metier FOREIGN KEY (metier_id) REFERENCES metier (id) ON DELETE CASCADE
);

CREATE TABLE service_order (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_user_id BIGINT      NOT NULL,
    metier_id      BIGINT      NOT NULL,
    service_id     BIGINT,
    message        TEXT,
    requested_date TIMESTAMP WITH TIME ZONE,
    status         VARCHAR(20) NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_service_order_client FOREIGN KEY (client_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_service_order_metier FOREIGN KEY (metier_id) REFERENCES metier (id),
    CONSTRAINT fk_service_order_service FOREIGN KEY (service_id) REFERENCES service (id)
);

CREATE TABLE metier_rating (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_user_id BIGINT   NOT NULL,
    metier_id      BIGINT   NOT NULL,
    rating         SMALLINT NOT NULL,
    comment        TEXT,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_metier_rating UNIQUE (metier_id, client_user_id),
    CONSTRAINT fk_metier_rating_client FOREIGN KEY (client_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_metier_rating_metier FOREIGN KEY (metier_id) REFERENCES metier (id) ON DELETE CASCADE
);

CREATE TABLE conversation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_user_id  BIGINT NOT NULL,
    metier_id       BIGINT NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    last_message_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_conversation UNIQUE (client_user_id, metier_id),
    CONSTRAINT fk_conversation_client FOREIGN KEY (client_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_conversation_metier FOREIGN KEY (metier_id) REFERENCES metier (id) ON DELETE CASCADE
);

CREATE TABLE message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender_user_id  BIGINT NOT NULL,
    body            TEXT   NOT NULL,
    sent_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    read_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_sender FOREIGN KEY (sender_user_id) REFERENCES app_user (id)
);

CREATE TABLE metier_gallery (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metier_id BIGINT  NOT NULL,
    file_id   BIGINT  NOT NULL,
    position  INTEGER,
    CONSTRAINT fk_metier_gallery_metier FOREIGN KEY (metier_id) REFERENCES metier (id) ON DELETE CASCADE,
    CONSTRAINT fk_metier_gallery_file FOREIGN KEY (file_id) REFERENCES media_file (id)
);

CREATE TABLE metier_social_media (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metier_id BIGINT       NOT NULL,
    platform  VARCHAR(50)  NOT NULL,
    url       VARCHAR(512) NOT NULL,
    CONSTRAINT fk_metier_social_media_metier FOREIGN KEY (metier_id) REFERENCES metier (id) ON DELETE CASCADE
);

CREATE TABLE hourly (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metier_id  BIGINT      NOT NULL,
    "day"      VARCHAR(10) NOT NULL,
    open_hour  TIME,
    close_hour TIME,
    is_open    BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_hourly_metier_day UNIQUE (metier_id, "day"),
    CONSTRAINT fk_hourly_metier FOREIGN KEY (metier_id) REFERENCES metier (id) ON DELETE CASCADE
);

-- ---------- Mobile : push & refresh tokens ----------

CREATE TABLE device_token (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    token        VARCHAR(512) NOT NULL,
    platform     VARCHAR(10)  NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_device_token_token UNIQUE (token),
    CONSTRAINT fk_device_token_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

-- ---------- Fermeture de la dépendance circulaire ----------

ALTER TABLE person
    ADD CONSTRAINT fk_person_photo FOREIGN KEY (photo_file_id) REFERENCES media_file (id);

ALTER TABLE media_file
    ADD CONSTRAINT fk_media_file_uploaded_by FOREIGN KEY (uploaded_by_user_id) REFERENCES app_user (id);

-- ============================================================================
--  Index : FK + colonnes de recherche
-- ============================================================================

-- Identité
CREATE INDEX idx_person_photo_file ON person (photo_file_id);
CREATE INDEX idx_media_file_uploaded_by ON media_file (uploaded_by_user_id);
CREATE INDEX idx_app_user_person ON app_user (person_id);
CREATE INDEX idx_user_role_role ON user_role (role_id);

-- Catégories
CREATE INDEX idx_category_parent ON category (parent_id);

-- Metier & recherche géoloc / publication
CREATE INDEX idx_metier_owner ON metier (owner_user_id);
CREATE INDEX idx_metier_address ON metier (address_id);
CREATE INDEX idx_metier_cover ON metier (cover_file_id);
CREATE INDEX idx_metier_is_published ON metier (is_published);
CREATE INDEX idx_metier_gps ON metier (gps_lat, gps_lng);
CREATE INDEX idx_metier_rating_avg ON metier (rating_avg);

-- Jointures & dépendances metier
CREATE INDEX idx_metier_category_category ON metier_category (category_id);
CREATE INDEX idx_service_metier ON service (metier_id);
CREATE INDEX idx_service_order_client ON service_order (client_user_id);
CREATE INDEX idx_service_order_metier ON service_order (metier_id);
CREATE INDEX idx_service_order_service ON service_order (service_id);
CREATE INDEX idx_metier_rating_metier ON metier_rating (metier_id);
CREATE INDEX idx_metier_rating_client ON metier_rating (client_user_id);
CREATE INDEX idx_conversation_client ON conversation (client_user_id);
CREATE INDEX idx_conversation_metier ON conversation (metier_id);
CREATE INDEX idx_message_conversation ON message (conversation_id);
CREATE INDEX idx_message_sender ON message (sender_user_id);
CREATE INDEX idx_metier_gallery_metier ON metier_gallery (metier_id);
CREATE INDEX idx_metier_gallery_file ON metier_gallery (file_id);
CREATE INDEX idx_metier_social_media_metier ON metier_social_media (metier_id);
CREATE INDEX idx_hourly_metier ON hourly (metier_id);

-- Mobile
CREATE INDEX idx_device_token_user ON device_token (user_id);
CREATE INDEX idx_refresh_token_user ON refresh_token (user_id);
