-- ============================================================================
--  Faso Tuuma — V2 : rôles applicatifs + code de réinitialisation de mot de passe
--  SQL portable H2 (dev, fichier) + PostgreSQL (prod).
-- ============================================================================

-- ---------- Rôles de base (V1 crée la table mais ne l'alimente pas) ----------
INSERT INTO role (name) VALUES ('CLIENT');
INSERT INTO role (name) VALUES ('ARTISAN');
INSERT INTO role (name) VALUES ('ADMIN');

-- ---------- Code de réinitialisation de mot de passe (6 chiffres, hashé) ----------
CREATE TABLE password_reset_code (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    code_hash   VARCHAR(255) NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_password_reset_code_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_code_user ON password_reset_code (user_id);
