-- ============================================================================
--  Faso Tuuma — V4 : notation automatique par IA (Gemini) + recherche sémantique
--  SQL portable H2 (dev, fichier) + PostgreSQL (prod).
--
--  Décisions de cadrage :
--    - Les avis portent désormais sur les SERVICES de l'artisan (et non sur
--      l'enseigne). La note affichée d'un service est calculée par l'IA
--      (sentiment + pondération + anti-faux-avis), de façon asynchrone.
--    - L'enseigne (metier) n'a plus de note globale propre : les colonnes
--      metier.rating_avg / rating_count et l'ancienne table metier_rating
--      sont retirées.
--    - Recherche sémantique : embedding sérialisé (JSON) stocké sur metier,
--      similarité cosinus calculée côté application.
-- ============================================================================

-- ---------- Notation des services (remplace metier_rating) ----------

CREATE TABLE service_rating (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id        BIGINT       NOT NULL,
    client_user_id    BIGINT       NOT NULL,
    star_rating       SMALLINT      NOT NULL,            -- étoile saisie par le client (1-5)
    comment           TEXT,
    -- Résultats de l'analyse IA (null tant que non traité) :
    ai_rating         SMALLINT,                          -- note 1-5 dérivée du texte
    sentiment_label   VARCHAR(20),                       -- POSITIVE / NEUTRAL / NEGATIVE
    sentiment_score   DECIMAL(3, 2),                     -- -1.00 .. 1.00
    mismatch          BOOLEAN       NOT NULL DEFAULT FALSE, -- décalage note/texte détecté
    weight            DECIMAL(3, 2) NOT NULL DEFAULT 1.00,  -- pondération dans l'agrégat (0..1)
    -- Modération (asynchrone) :
    status            VARCHAR(20)   NOT NULL DEFAULT 'PENDING', -- PENDING / APPROVED / REJECTED
    is_fake           BOOLEAN       NOT NULL DEFAULT FALSE,
    is_inappropriate  BOOLEAN       NOT NULL DEFAULT FALSE,
    moderation_reason TEXT,
    ai_processed_at   TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_service_rating UNIQUE (service_id, client_user_id),
    CONSTRAINT fk_service_rating_service FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE,
    CONSTRAINT fk_service_rating_client FOREIGN KEY (client_user_id) REFERENCES app_user (id)
);

CREATE INDEX idx_service_rating_service ON service_rating (service_id);
CREATE INDEX idx_service_rating_client ON service_rating (client_user_id);
CREATE INDEX idx_service_rating_status ON service_rating (status);

-- ---------- Note IA + synthèse au niveau service ----------

ALTER TABLE service ADD COLUMN rating_avg DECIMAL(2, 1) NOT NULL DEFAULT 0;
ALTER TABLE service ADD COLUMN rating_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE service ADD COLUMN ai_summary TEXT;
ALTER TABLE service ADD COLUMN ai_summary_updated_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX idx_service_rating_avg ON service (rating_avg);

-- ---------- Recherche sémantique : embedding de l'enseigne ----------

ALTER TABLE metier ADD COLUMN search_embedding TEXT;          -- vecteur sérialisé en JSON
ALTER TABLE metier ADD COLUMN embedding_updated_at TIMESTAMP WITH TIME ZONE;

-- ---------- Retrait de la note au niveau enseigne ----------

DROP INDEX IF EXISTS idx_metier_rating_avg;
ALTER TABLE metier DROP COLUMN rating_avg;
ALTER TABLE metier DROP COLUMN rating_count;

DROP TABLE IF EXISTS metier_rating;
