-- ============================================================================
--  Faso Tuuma — V5 : numéros de téléphone multiples, favoris, tokens FCM,
--                    historique des notifications.
--  SQL portable H2 (dev, fichier) + PostgreSQL (prod).
--
--  Décisions de cadrage :
--    - Un metier peut avoir plusieurs numéros de contact, chacun marqué ou non
--      comme numéro WhatsApp. L'ancienne colonne metier.phone (un seul numéro)
--      est migrée dans metier_phone puis supprimée (source de vérité unique).
--    - Favoris : un utilisateur peut marquer des enseignes (au plus une fois).
--    - Notifications push (FCM) : historique persisté des notifications (centre
--      de notifications mobile). La table device_token (tokens d'appareil) existe
--      déjà depuis V1__init et n'est PAS recréée ici.
-- ============================================================================

-- ---------- Numéros de téléphone du metier (remplace metier.phone) ----------

CREATE TABLE metier_phone (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metier_id   BIGINT      NOT NULL,
    number      VARCHAR(30) NOT NULL,
    is_whatsapp BOOLEAN     NOT NULL DEFAULT FALSE,
    label       VARCHAR(60),
    CONSTRAINT fk_metier_phone_metier FOREIGN KEY (metier_id) REFERENCES metier (id) ON DELETE CASCADE
);

CREATE INDEX idx_metier_phone_metier ON metier_phone (metier_id);

-- Migration des numéros existants (non vides) vers la nouvelle table.
INSERT INTO metier_phone (metier_id, number, is_whatsapp)
    SELECT id, phone, FALSE FROM metier WHERE phone IS NOT NULL AND phone <> '';

ALTER TABLE metier DROP COLUMN phone;

-- ---------- Favoris (utilisateur ↔ enseigne) ----------

CREATE TABLE user_favorite_metier (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_user_id BIGINT NOT NULL,
    metier_id      BIGINT NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_favorite UNIQUE (client_user_id, metier_id),
    CONSTRAINT fk_favorite_user FOREIGN KEY (client_user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_favorite_metier FOREIGN KEY (metier_id) REFERENCES metier (id) ON DELETE CASCADE
);

CREATE INDEX idx_favorite_metier ON user_favorite_metier (metier_id);

-- ---------- Historique des notifications ----------

CREATE TABLE notification (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT       NOT NULL,
    type              VARCHAR(30)  NOT NULL,            -- NEW_REVIEW / ORDER_STATUS / NEW_MESSAGE
    title             VARCHAR(150) NOT NULL,
    body              TEXT,
    data_json         TEXT,                             -- charge utile de navigation (ids cibles)
    read_at           TIMESTAMP WITH TIME ZONE,         -- non nul ⇒ lue
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE INDEX idx_notification_recipient ON notification (recipient_user_id);
