-- ============================================================================
--  Faso Tuuma — V6 : notation des commerces (metier_rating)
--  Les avis portent sur l'enseigne, pas sur une prestation individuelle.
-- ============================================================================

CREATE TABLE metier_rating (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metier_id         BIGINT       NOT NULL,
    client_user_id    BIGINT       NOT NULL,
    star_rating       SMALLINT     NOT NULL,
    comment           TEXT,
    ai_rating         SMALLINT,
    sentiment_label   VARCHAR(20),
    sentiment_score   DECIMAL(3, 2),
    mismatch          BOOLEAN      NOT NULL DEFAULT FALSE,
    weight            DECIMAL(3, 2) NOT NULL DEFAULT 1.00,
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    is_fake           BOOLEAN      NOT NULL DEFAULT FALSE,
    is_inappropriate  BOOLEAN      NOT NULL DEFAULT FALSE,
    moderation_reason TEXT,
    ai_processed_at   TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_metier_rating UNIQUE (metier_id, client_user_id),
    CONSTRAINT fk_metier_rating_metier FOREIGN KEY (metier_id) REFERENCES metier (id) ON DELETE CASCADE,
    CONSTRAINT fk_metier_rating_client FOREIGN KEY (client_user_id) REFERENCES app_user (id)
);

CREATE INDEX idx_metier_rating_metier ON metier_rating (metier_id);
CREATE INDEX idx_metier_rating_client ON metier_rating (client_user_id);
CREATE INDEX idx_metier_rating_status ON metier_rating (status);

ALTER TABLE metier ADD COLUMN rating_avg DECIMAL(2, 1) NOT NULL DEFAULT 0;
ALTER TABLE metier ADD COLUMN rating_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE metier ADD COLUMN ai_summary TEXT;
ALTER TABLE metier ADD COLUMN ai_summary_updated_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX idx_metier_rating_avg ON metier (rating_avg);
